version: "3.3"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "masterKeyKeyKey123"
      MEILI_ENV: "development"
    volumes:
      - meili_data:/meili_data
    networks:
      - search_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local_search_api
    ports:
      - "8880:8000"
    environment:
      DATABASE_URL: "sqlite:////app/data/local_search.db"
      MEILI_HOST: "http://meilisearch:7700"
      MEILI_MASTER_KEY: "masterKeyKeyKey123"
      CUDA_VISIBLE_DEVICES: "0"  # Explicitly use first GPU
    depends_on:
      meilisearch:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./app:/app  # For development hot-reloading
    networks:
      - search_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  meili_data:

networks:
  search_network:
    driver: bridge